### ISSUE TITLE
请问，要给下拉框动态赋值，要调用什么方法？

### ISSUE THREAD

**Issue by ll1211** [leezng/element-patch#24]
请问，要给下拉框动态赋值，要调用什么方法？

**Comment by leezng** [comment]
请参照README文档

**Comment by chigco** [comment]
同问，我也看不懂怎么动态下拉框动态赋值

**Comment by leezng** [comment]
当前的设计下只能通过触发 `created` 钩子，这也是设计上所导致的一个问题

**Comment by chigco** [comment]
updateValue如何调用，我现在是直接this.data.searchForm[x].$options 赋值。感觉很奇怪
