### ISSUE TITLE
大佬你好，有几个问题咨询下

### ISSUE THREAD

**Issue by chenmychou** [leezng/element-patch#38]
1.现在往select中动态加载下拉数据貌似不能用setOptions方法了，应该如何处理？现在这个patch有没有实现？
2.现在全是单列渲染，是否能支持多列渲染？
3.content里能否也直接渲染button组件并添加事件（比如确认提交，取消之类的）？
万分感谢！

**Comment by leezng** [comment]
setOptions方法不在这个git里，是其他fork版本的功能
多列渲染是个好建议，未来应该会支持
content的定义是用来渲染表单的，如果要添加其他组件，可以在slot里使用

**Comment by chenmychou** [comment]
感谢回复，表单里有上传组件怎么搞，目前好像也不支持component属性了？
